# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.24.1
# 

Name:       tmpwatch

# >> macros
# << macros

Summary:    A utility for removing files based on when they were last accessed
Version:    2.11
Release:    1
Group:      System/Base
License:    GPLv2
URL:        https://fedorahosted.org/tmpwatch/
Source0:    https://fedorahosted.org/releases/t/m/tmpwatch/%{name}-%{version}.tar.bz2
Source1:    tmpwatch.daily
Source100:  tmpwatch.yaml
Requires:   psmisc

%description
The tmpwatch utility recursively searches through specified
directories and removes files which have not been accessed in a
specified period of time.  Tmpwatch is normally used to clean up
directories which are used for temporarily holding files (for example,
/tmp).  Tmpwatch ignores symlinks, won't switch filesystems and only
removes empty directories and regular files.



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
autoreconf -v -i -f
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
#make ROOT=%{buildroot} SBINDIR=%{_sbindir} MANDIR=%{_mandir} install

mkdir -p %{buildroot}/etc/cron.daily
cp %{SOURCE1} %{buildroot}/etc/cron.daily/tmpwatch
chmod +x %{buildroot}/etc/cron.daily/tmpwatch
# << install post


%files
%defattr(-,root,root,-)
# >> files
%doc ChangeLog NEWS README
%{_sbindir}/tmpwatch
%doc %{_mandir}/man8/tmpwatch.8*
%config(noreplace) /etc/cron.daily/tmpwatch
# << files
